import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Manrope } from 'next/font/google';
import "./globals.css";


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight:["400","500","600","700"]
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight:["400","500","600","700"]

});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} ${inter.variable} antialiased`}
      >
       <div className = " flex flex-col min-h-screen ">
        <main className = "flex-1 bg-background text-foreground">
          {children}
        </main>
       </div>
      </body>
    </html>
  );
}
